version: '3.8'

services:
  app1:
    build:
      context: "8000"
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - backend
  app2:
    build:
      context: "8001"
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    networks:
      - backend


  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - backend
    depends_on:
      - app1
      - app2

  mongodb:
    container_name: mask-mongodb
    image: mongo
    ports:
      - "27107:27107"
    restart: always
    volumes:
      - "./:/mask/"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    networks:
      - backend

networks:
  backend:
    driver: bridge