server:
  port : 8000
spring:
  ai:
    url: http://localhost:8888/api/ai/voice/
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      database : mask

  redis:
#    host: redis
    host: 127.0.0.1
    port: 6379